apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-website-deployment
  labels:
    app: insurance-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insurance-website
  template:
    metadata:
      labels:
        app: insurance-website
    spec:
      containers:
        - name: insurance-website-container
          image: your-docker-image:tag
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "0.5"
              memory: "256Mi"
          ports:
            - containerPort: 80
