apiVersion: v1
kind: Service
metadata:
  name: insurance-website-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: insurance-website
